server:
  port: 8080
spring:
  application:
    name: fileManager
  http:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  #  thymeleaf:
  #    mode: HTML5
  #    cache: false #开发时关闭缓存,不然没法看到实时页面
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      remove-abandoned-timeout: 20
      #url: jdbc:mysql://localhost:3306/file_manager
      url: jdbc:mysql://localhost:3306/test



