server:
  port: 8080
spring:
  application:
    name: springboot-study

#数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root123
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#redis配置
  redis:
#    host: 47.113.111.240
    host: 127.0.0.1
    port: 6379
    timeout: 3        #连接超时时间（毫秒）
    poolMaxTotal: 10  #连接池中的最大连接数
    poolMaxIdle : 10  #连接池中的最大空闲连接
    poolMaxWait : 3   #连接池最大阻塞等待时间（使用负值表示没有限制）

  rocketmq:
    name-server: 127.0.0.1:9876
    # 生产者
    producer:
      group: boot_group_1
      # 消息发送超时时间
      send-message-timeout: 3000
      # 消息最大长度4M
      max-message-size: 4096
      # 消息发送失败重试次数
      retry-times-when-send-failed: 3
      # 异步消息发送失败重试次数
      retry-times-when-send-async-failed: 2
    # 消费者
    consumer:
      group: boot_group_1
      # 每次提取的最大消息数
      pull-batch-size: 5



#logging:
#  level: info

#org:
#  apache:
#    commons:
#      logging:
#        simplelog:
#          defaultlog: info


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    passowrd: guest
#    virtualHost: /



