server:
  port: 8080
spring:
  application:
    name: haoziyuan

#  数据源
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      remove-abandoned-timeout: 20
      url: jdbc:mysql://localhost:3306/iotest

#ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
    servlet:
      #内容类别,可不用配置
      content-type: text/html
